version: '3.1'

services:
  database:
    container_name: db-api-poup
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: poup
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin