version: '3.1'

services:
  api-poup:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: api-poup
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - database
    links:
      - database
    networks:
      - api-connection

  database:
    container_name: db-api-poup
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: poup
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - api-connection

networks:
  api-connection:
    name: api-poup-network